spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: ${username}
    password: ${password}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: true
    show-sql: true
    generate-ddl: true