spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: ${{ secrets.USERNAME }}
    password: ${{ secrets.PASSWORD }}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: true
    show-sql: true
    generate-ddl: true
