name: Java CI with Gradle

on:
  push:
    branches:
      - master
  pull_request:
    branches: 
      - master

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Replace secrets in application.yml
      run: |
        sed -i "s/\${{ secrets.USERNAME }}/$USERNAME/g" path/to/your/application.yml
        sed -i "s/\${{ secrets.PASSWORD }}/$PASSWORD/g" path/to/your/application.yml
      env:
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
    - name: Run unit tests
      run: ./gradlew -x test
